Update written content, add links, icons, tech-stacks
zantetsuken88/lee-stewart pull request #4
Opened 2020-12-09 12:08 UTC by zantetsuken88

Changes viewable [here](https://zantetsuken88.github.io/lee-stewart/)

- Major overhaul of written content which hadn't really been updated for quite a few years. Updates should include a more tangible sense of my personal achievements/impact in previous roles, more targeted references to particular tech.
- Added a couple of tooltips to elaborate certain terminology where inclusion in the main text felt excessive. 
- Added icons for each company that links to their website on click. 
- Added animated tech stack drawer where relevent

2020-12-09 12:10 UTC, zantetsuken88 commented
The large number of files changed is misleading! Many of them are images/svg icons which don't need to be code reviewed, plus config files etc.

2020-12-17 11:22 UTC, julesnuggy commented on src/components/RoleSection.jsx
> +            }/>
The `/>` should be on a new line

2020-12-17 11:42 UTC, julesnuggy requested changes
Looks good - just a few minor points mostly about linting.

It would be good if you could also:
1) Include a link to your actual CV website in the README and probably also your Github profile - it's very hard to search for / find it at the moment. In fact, the README probably shouldn't have any of the React auto-generated text.

2) The company link Chip components are a bit confusing. They look and behave like buttons but you have to click on the text to be taken to the company website. It would be more intuitive / better UI/UX if clicking just the pill itself took you to the website.

2020-12-17 11:42 UTC, julesnuggy commented on src/components/RoleSection.jsx
>              label={<Typography variant='body2'>{data.yearRange}</Typography>}/>
These 3 `/>` should be on a new line

2020-12-17 11:42 UTC, julesnuggy commented on src/components/RoleSection.jsx
> +            </Typography>;
An immediate return would be neater :-)

2020-12-17 11:42 UTC, julesnuggy commented on src/components/RoleSection.jsx
> +          )}
This should be grouped with previous `}`

2020-12-17 11:42 UTC, julesnuggy commented on src/components/TechStack.jsx
> +        { <Icons iconClass={iconClass}/> }
I don't think these `{ }` are necessary?

2020-12-17 11:42 UTC, julesnuggy commented on src/components/TechStack.jsx
> +      <button className={`stack-button ${buttonSelected}`} onClick={() => handleClick()}><Typography variant='caption'>Tech Stack</Typography></button>
This is a very long line - would be better to structure it out.

2020-12-17 11:42 UTC, julesnuggy commented on src/media/techicons/TechIcons.jsx
> +// Starling Logos
I think this comment is redundant now?

2021-01-21 17:32 UTC, merged